services:
  - type: web
    name: changebox-facerecognition-heartbeat-dashboard
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn heartbeat_server:app"
